// Name: Maryna Sobol 
// Student ID: C00312784 
// Date: March 2026
// Purpose: This class is used to initialize cat objects with their respective attributes.

public class Initialization 
{
    private final int catID; // Unique identifier for each cat, auto-incremented in the database
    private final String catName; // Name of the cat
    private final String catDetails; // Details about the cat
    private final int catAge; // Age of the cat
    private final float catPrice; // Price of the cat
    private final String catStatus; // Status of the cat (e.g., Available, Sold)
    private final int userID; // ID of the user who owns the cat    

    public Initialization(int id, String name, String details, int age, float price, String status, int uID) 
    {
        this.catID = id; // ID is typically auto-generated by the database, but we include it here for completeness 
        this.catName = name; // Name is required
        this.catDetails = details; // Details can be optional, but we allow it to be set
        this.catAge = age; // Age is required
        this.catPrice = price; // Price is required
        this.catStatus = status; // Status is required, but we can set a default value like "Available" if not provided
        this.userID = uID; // User ID is required to link the cat to its owner, but we can set a default value like 0 if not provided
    }

    // Getters
    public int getCatID() { return catID; } 
    public String getCatName() { return catName; } 
    public String getCatDetails() { return catDetails; }
    public int getCatAge() { return catAge; }
    public float getCatPrice() { return catPrice; }
    public String getCatStatus() { return catStatus; }
    public int getUserID() { return userID; }
}